In [1]:
import sys
import os
import path
import time
import re
import numpy as np
import json
import gzip
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
import unidecode
import joblib


In [2]:

total=0
allComment=[]

# f = open("comments.json")
# data = json.load(f)
# for i in (data['data']):
#     for j in i:
#         allComment.append(j)
#         total=total+1

# f = open("comments1.json")
# data1 = json.load(f)
# for i in (data1['data']):
#     for j in i:
#         allComment.append(j)
#         total=total+1

f = open("data.json", encoding="utf8")
data2 = json.load(f)
for i in (data2['data']):
    for j in i:
        allComment.append(j)
        total=total+1
print(total)
print(allComment[0])

4577
{'star': 5, 'content': 'Thầy nói chậm, chắc, có điểm nhấn nên dễ tiếp thu\nCách xưng hô ngộ, nhưng giúp mình liên tưởng tình huống dễ dàng.\nKhóa level 1 tuyệt! Vừa học xong là mình áp dụng giải quyết mâu thuẫn với ck được luôn. Vì 2 vk ck đang chiến tranh lạnh mới tìm đến khóa học này nè.\nMới xem bài học thử thôi mà hay quá nên lập tức mua nguyên khóa học hết trong đêm.\nTuyệt quá thầy Cường ơi! \nCho em biết thêm về khóa level 2 và 3 nhé!\nCảm ơn thầy!!'}


In [3]:
contents=[]
stars=[]
for i in range(0,len(allComment)):
    contents.append(unidecode.unidecode(allComment[i]['content']).lower())
    stars.append(allComment[i]['star'])


In [4]:
vectorizer = CountVectorizer()
vectorizer.fit(contents)
# print(vectorizer.vocabulary_)
X_train = vectorizer.transform(contents)
print(X_train.shape)
print(type(X_train))
print(X_train.toarray()[0])

(4577, 1401)
<class 'scipy.sparse.csr.csr_matrix'>
[0 0 0 ... 0 0 0]


In [5]:
y_train=[]

numNega=0
numPosi=0
for i in stars:
    if(i<=3):
        y_train.append(0)
        numNega=numNega+1
    else:
        y_train.append(1)
        numPosi=numPosi+1
print(numNega)
print(numPosi)
print(len(y_train))

184
4393
4577


In [6]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

In [7]:
print(classifier.predict(vectorizer.transform(["hang bi loi kem chat luong"])))

[1]


In [8]:
# tach ra 500 xau
y_train=[]
x_train=[]
x_train_bad=[]
x_train_good=[]

total=0
for i in range(0,len(stars)):
    if(stars[i]<=3):
        if(contents[i] not in x_train_bad):
            y_train.append(0)
            x_train_bad.append(contents[i])
            x_train.append(contents[i])
            total=total+1
    if(total==500):
        break
print(len(y_train))
print(len(list(set(x_train_bad))))

total=0
for i in range(0,len(stars)):
    if(stars[i]>3):
        if(contents[i] not in x_train_good):
            y_train.append(1)
            x_train_good.append(contents[i])
            x_train.append(contents[i])
            total=total+1
    if(total==len(x_train_bad)):
        break
print(len(y_train))
print(len(x_train))
# np.save("CleanedData/x_train.npy",x_train)
# np.save("CleanedData/y_train.npy",y_train)

print(len(list(set(x_train_good))))


175
175
350
350
175


In [9]:
vectorizer = CountVectorizer()
vectorizer.fit(x_train)
print(vectorizer.vocabulary_)
X_train = vectorizer.transform(x_train)
print(X_train.shape)
print(type(X_train))

{'khong': 248, 'the': 477, 'mo': 315, 'noi': 373, 'video': 563, 'de': 114, 'xem': 587, 'bai': 27, 'giang': 176, 'tuong': 541, 'doi': 132, 'on': 379, 'dung': 140, 'rat': 417, 'thiet': 484, 'thuc': 493, 'khoa': 245, 'hoc': 218, 'cung': 97, 'hay': 202, 'nhung': 368, 'nhieu': 363, 'phan': 390, 'thay': 475, 'va': 551, 'day': 112, 'lam': 264, 'ma': 295, 'biet': 38, 'kich': 252, 'cho': 71, 'nao': 329, 'luon': 290, 'tam': 457, 'that': 474, 'tuyet': 543, 'voi': 571, 'nam': 326, 'phuong': 399, 'xin': 589, 'tran': 522, 'trong': 533, 'cam': 50, 'hop': 221, 'ly': 294, 'toi': 514, 'tren': 526, 'dien': 123, 'thoai': 487, 'tai': 456, 've': 559, 'dc': 113, 'la': 261, 'tap': 461, 'tin': 508, 'coi': 86, 'duoc': 141, 'thi': 481, 'sao': 433, 'ad': 14, 'du': 138, 'gian': 175, 'trai': 520, 'chua': 76, 'dao': 108, 'sau': 436, 'kien': 254, 'may': 305, 'ban': 29, 'moi': 316, 'buoc': 44, 'dau': 111, 'tim': 506, 'hieu': 209, 'kinh': 256, 'doanh': 130, 'chat': 62, 'luong': 291, 'tot': 517, 'phu': 397, 'da': 101, '

In [10]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(X_train, y_train)


LogisticRegression()

In [13]:
text = "ok"
content=[]

f = open("data.json", encoding="utf8")
data3 = json.load(f)
for i in (data3['data']):
    for j in i:
        print(j['content'])
        print(classifier.predict(vectorizer.transform(['content'])))
        print(classifier.predict_proba(vectorizer.transform(['content'])))

Thầy nói chậm, chắc, có điểm nhấn nên dễ tiếp thu
Cách xưng hô ngộ, nhưng giúp mình liên tưởng tình huống dễ dàng.
Khóa level 1 tuyệt! Vừa học xong là mình áp dụng giải quyết mâu thuẫn với ck được luôn. Vì 2 vk ck đang chiến tranh lạnh mới tìm đến khóa học này nè.
Mới xem bài học thử thôi mà hay quá nên lập tức mua nguyên khóa học hết trong đêm.
Tuyệt quá thầy Cường ơi! 
Cho em biết thêm về khóa level 2 và 3 nhé!
Cảm ơn thầy!!
[1]
[[0.48915385 0.51084615]]
Bài họ hay và bổ ích nên chia sẻ để nhiều người biết đến hơn
[1]
[[0.48915385 0.51084615]]
Khóa học này thực sự rất chất lượng, có rất nhiều kiến thức!
[1]
[[0.48915385 0.51084615]]
Rất hữu ích, đáng học, cảm ơn unica!
[1]
[[0.48915385 0.51084615]]
Rất hay, cảm ơn thầy! 5s này
[1]
[[0.48915385 0.51084615]]
rat hay cam on thayd a day em 
[1]
[[0.48915385 0.51084615]]
Khóa học rất hữu ích, Cám ơn Thầy nhiều!
[1]
[[0.48915385 0.51084615]]
nội dung đầy đủ nhưng giảng không hay
[1]
[[0.48915385 0.51084615]]
khóa học LẬP TRÌNH WORDPRESS TH

[[0.48915385 0.51084615]]
Giảng viên vui tính, giảng hay.
[1]
[[0.48915385 0.51084615]]
Minh đả học thử và thấy rất hửu ích
[1]
[[0.48915385 0.51084615]]
Đang học thử, hy vọng là sẽ ổn với mọi người muốn học từ đầu
[1]
[[0.48915385 0.51084615]]
bài giảng hay và dễ hiểu
[1]
[[0.48915385 0.51084615]]
Rất hay, cảm ơn cô Thảo Trần
[1]
[[0.48915385 0.51084615]]
hoc de hieu va hieu qua
[1]
[[0.48915385 0.51084615]]
tuyệt vời ạ
cảm ơn cô giáo

[1]
[[0.48915385 0.51084615]]
hay qua a. em hoc tot hon nhieu lam


[1]
[[0.48915385 0.51084615]]
Cô dạy hay dễ hiểu, nhiều kiến thức bổ ích
[1]
[[0.48915385 0.51084615]]
Rất tốt
[1]
[[0.48915385 0.51084615]]
Khoá học rất hay cho bạn mất gốc
[1]
[[0.48915385 0.51084615]]
verry good
rất có ích
[1]
[[0.48915385 0.51084615]]
Khoá học quá tuyệt vời. Cám ơn unica nhiều.
[1]
[[0.48915385 0.51084615]]
asdfghjFGHFGHJKLKadsdaadasa
[1]
[[0.48915385 0.51084615]]
tuyệt vời
[1]
[[0.48915385 0.51084615]]
Cô đã xinh lại còn dậy hay nữa
[1]
[[0.48915385 0.51084615

[[0.48915385 0.51084615]]
cảm ơn giảng viên................
[1]
[[0.48915385 0.51084615]]
quas hay so vowi quy dinh
[1]
[[0.48915385 0.51084615]]
good

[1]
[[0.48915385 0.51084615]]
hay
[1]
[[0.48915385 0.51084615]]
Good
[1]
[[0.48915385 0.51084615]]
ok
[1]
[[0.48915385 0.51084615]]
Nhiều bài học thực tế và bổ ích
[1]
[[0.48915385 0.51084615]]
kha hay nen thuc hanh moi cho ra ket qua
[1]
[[0.48915385 0.51084615]]
KHỞI NGHIỆP KINH DOANH VỚI 50 TRIỆU
[1]
[[0.48915385 0.51084615]]
hay, dễ hiểu
[1]
[[0.48915385 0.51084615]]
nội dung đầy đủ, giàn trải, nhưng chưa đào sâu kiến thức lắm. hợp cho mấy bạn mới bước đầu tìm hiểu kinh doanh.
[1]
[[0.48915385 0.51084615]]
RẤT TUYỆT VỜI. CẢM ƠN THẦY!
[1]
[[0.48915385 0.51084615]]
Rất hâm mộ Thầy Hán Quang Dự - Người luôn nhiệt huyết, tràn đầy năng lượng và cháy hết mình dù là khóa học offline hay online. Cảm ơn thầy đã cung cấp những kiến thức hết sức bổ ích và thực tế để có thể áp dụng và có kết quả ngay.
[1]
[[0.48915385 0.51084615]]
Cảm ơn Thầy n

cảm ơn thày cung cấp thông tin hữu ích
[1]
[[0.48915385 0.51084615]]
rat de hieu va hay nua cam on 
[1]
[[0.48915385 0.51084615]]
Khóa học rất bổ ích. Cảm ơn!
[1]
[[0.48915385 0.51084615]]
Chúc bạn có những trải nghiệm tuyệt vời cùng Unica.

ĐÁNH GIÁ KHÓA HỌC (+2 ĐIỂM)

Đánh giá /5 sao: 

Nhập nội dung đánh giá của bạn tại đây để giúp Unica ngày càng phục vụ học viên tốt hơn (tối thiểu 20 kí tự)


[1]
[[0.48915385 0.51084615]]
thầy dạy hay dễ hiểu đặc biệt khác lôi cuốn. Cảm ơn thầy mong thầy ra nhiều khóa học hơn
[1]
[[0.48915385 0.51084615]]
ĐÁNH GIÁ KHÓA HỌC (+2 ĐIỂM)
[1]
[[0.48915385 0.51084615]]
Khóa học tuyệt vời. OKKKKKK
[1]
[[0.48915385 0.51084615]]
khoa hoc bo ich danh cho nguoi moi bat dau 
[1]
[[0.48915385 0.51084615]]
rat chi tiet den noi khong tin duoc
[1]
[[0.48915385 0.51084615]]
Khoa hoc rat la huu ich
[1]
[[0.48915385 0.51084615]]
kho hoc theo, de nan nua
[1]
[[0.48915385 0.51084615]]
Bài giảng chi tiết. Hay
[1]
[[0.48915385 0.51084615]]
Bài học rất là hay
[1]
[[0.4891

[[0.48915385 0.51084615]]
Rất tâm đắc.
[1]
[[0.48915385 0.51084615]]
Vượt trên cả sự mong đợi !!! Khóa học tuyệt vời !!!
[1]
[[0.48915385 0.51084615]]
khóa học rất hay và cụ thể, cám ơn thầy Phạm Thành Long!
[1]
[[0.48915385 0.51084615]]
Bài học rất  tuyệt  vời  cảm  ơn  thầy  phạm  thành  *g
[1]
[[0.48915385 0.51084615]]
Tuyệt
[1]
[[0.48915385 0.51084615]]
Cảm ơn thầy rất hay
[1]
[[0.48915385 0.51084615]]
Tuyệt vời, e cám ơn Thầy
[1]
[[0.48915385 0.51084615]]
thầy thật tuyệt vời
[1]
[[0.48915385 0.51084615]]
hay quá
[1]
[[0.48915385 0.51084615]]
nội dung thiết thực, áp dụng được! Tuy nhiên ở phần *gpt.com/emailbook thì website không tồn tại và một số tài liệu khác được giới thiệu trong bài cũng vậy.
[1]
[[0.48915385 0.51084615]]
Hay, huu dung. Cam on thay
[1]
[[0.48915385 0.51084615]]
Tuyệt cú mèo lắm lắm hehe.
[1]
[[0.48915385 0.51084615]]
xin gửi lời cảm ơn chân thành đến thầy Thành Long và tập thể UNICA !khóa học thật sự quá tuyệt vời,công việc kinh doanh của tôi đang thay đổi rõ r

[1]
[[0.48915385 0.51084615]]
cơ bản
[1]
[[0.48915385 0.51084615]]
 KHông biết có chương trình nâng cao hơn không hả UNICa. Chứ những cái này tôi nghĩ nó chỉ là cơ bản thôi. Có chương trình nâng cao về đàm phán ,xử lý từ chối trong bán hàng thì tuyệt. 
[1]
[[0.48915385 0.51084615]]
Không hay 
[1]
[[0.48915385 0.51084615]]
Khóa học rất hay và bổ ích, cám ơn thầy!
[1]
[[0.48915385 0.51084615]]
Thầy giảng bài rất dễ hiểu, các ví dụ rất cụ thể sát với thực tế
[1]
[[0.48915385 0.51084615]]
Cảm ơn thầy bải giảng rất dễ hiểu
[1]
[[0.48915385 0.51084615]]
Khóa học rất hay, cám ơn tác giả, cám ơn Unica
[1]
[[0.48915385 0.51084615]]
khóa học rất hay, thích hợp chon những bạn muốn học lại căn bản về excel. Tks thầy vs Unica ...
[1]
[[0.48915385 0.51084615]]
Bài học rất lí thú.Đặc biệt là cách truyền đạt dí dỏm của Thầy.
[1]
[[0.48915385 0.51084615]]
Rất tốt! Bài giảng rất chi tiết và dễ hiểu, nhiều kiến thức hay và thực tế! Xin cảm ơn thầy Hoàng rất nhiều, khóa học rất có ích với tôi
[1]
[[0.4891

[[0.48915385 0.51084615]]
Hay quá thầy
[1]
[[0.48915385 0.51084615]]
Good
[1]
[[0.48915385 0.51084615]]
Rất tốt dễ hiểu
[1]
[[0.48915385 0.51084615]]
Tốt lắm anh ơi
[1]
[[0.48915385 0.51084615]]
quá hay ạ, có thể vừa học vừa thưc hành theo ạ
[1]
[[0.48915385 0.51084615]]
Tuyệt
[1]
[[0.48915385 0.51084615]]
Rất hay vs dễ hiểu . Thanks haketu
[1]
[[0.48915385 0.51084615]]
Khoá học dạy hơi nhanh
[1]
[[0.48915385 0.51084615]]
Perfect:'>
[1]
[[0.48915385 0.51084615]]
Khoá học rất hay
[1]
[[0.48915385 0.51084615]]
Bài giảnh hay
[1]
[[0.48915385 0.51084615]]
Anh dạy rất hay, rất dễ học
[1]
[[0.48915385 0.51084615]]
Rất tốt ạ. Dễ hiểu , bài tập dễ áp dụng , mọi người nên đăng kí ạ . ????????
[1]
[[0.48915385 0.51084615]]
Hay và dễ hiểu
[1]
[[0.48915385 0.51084615]]
Chỉ đơn giản là thích anh Haketu thôi
[1]
[[0.48915385 0.51084615]]
Khoá học hay, dành cho những bạn chưa biết gì.
[1]
[[0.48915385 0.51084615]]
Chi tiết và rất cần thiết
[1]
[[0.48915385 0.51084615]]
khoá học ý nghĩa với các 

[[0.48915385 0.51084615]]
TUYỆT CHIÊU LUYỆN REVIT ARCH
[1]
[[0.48915385 0.51084615]]
CÁM ƠN ANH LƯƠNG - NHƯNG CÓ VIDEO KHÔNG CÓ THUYẾT MINH 
[1]
[[0.48915385 0.51084615]]
Khóa học hay
[1]
[[0.48915385 0.51084615]]
xin link download phần mềm revit đang học
[1]
[[0.48915385 0.51084615]]
Chưa ngắn gọn xúc tích và k có file mẫu dự án để người học mở file lên rồi làm theo
[1]
[[0.48915385 0.51084615]]
Ok
[1]
[[0.48915385 0.51084615]]
quảng cáo và thực tế tỉ lệ 10-2
[1]
[[0.48915385 0.51084615]]
mình đang học và thấy rất hay hy vọng sẽ cảm thụ được hết những nội dung mà anh dạy
[1]
[[0.48915385 0.51084615]]
Khóa học hữu ích và thực tế
[1]
[[0.48915385 0.51084615]]
Cảm ơn thầy khóa học của thầy rất hay, nó giúp bản thân em thay đổi rất nhiều trong cuộc sống và công việc
[1]
[[0.48915385 0.51084615]]
hay, chất lượng, đầy đủ
[1]
[[0.48915385 0.51084615]]
Đây là khóa vô cùng hữu ích, tôi như bừng sáng lên và khai mở rất nhiều điều - những sai lầm trong tư duy kinh doanh của tôi
[1]
[[0.48915385 

[[0.48915385 0.51084615]]
Như lồn
[1]
[[0.48915385 0.51084615]]
cảm ơn thầy ạ
[1]
[[0.48915385 0.51084615]]
Tuyệt vời!
[1]
[[0.48915385 0.51084615]]
Chương trình rất hay
[1]
[[0.48915385 0.51084615]]
khóa học chi tiết . nên cập nhật giao diện mới của fb nữa thầy ạ
[1]
[[0.48915385 0.51084615]]
Hay tốt
[1]
[[0.48915385 0.51084615]]
Hy
[1]
[[0.48915385 0.51084615]]
CÓ GIÁ TRỊ CHO CÁC NEWBIE . THANKS!
[1]
[[0.48915385 0.51084615]]
Toots
[1]
[[0.48915385 0.51084615]]
Okay
[1]
[[0.48915385 0.51084615]]
Tốt, bài học hữu ích giúp tôi đánh giá được hiệu quả của quảng cáo
[1]
[[0.48915385 0.51084615]]
chi tiết nhưng bài giảng đã cũ nhiều so với facebook hiện đại
[1]
[[0.48915385 0.51084615]]
Thầy dạy rất chi tiết
[1]
[[0.48915385 0.51084615]]
Bài giảng rất hay
[1]
[[0.48915385 0.51084615]]
khóa học chi tiết và dễ hiểu
[1]
[[0.48915385 0.51084615]]
Tạm dc
[1]
[[0.48915385 0.51084615]]
Dễ hiểu
[1]
[[0.48915385 0.51084615]]
Bài học hơi ngắn :(
[1]
[[0.48915385 0.51084615]]
Bài học rất hay và giúp 

zalo 0938 625 498
[1]
[[0.48915385 0.51084615]]
khóa học hay quá ạ. em cảm ơn thầy ạ
[1]
[[0.48915385 0.51084615]]
Các bài giảng của thầy rất tích cực và tràn đầy cảm xúc như chính tên gọi của nó, nhờ đó mà tôi cảm thấy mình lúc nào cũng luôn có cảm xúc tích cực chạy trong cơ thể, để rồi lại hút những cảm xúc tích cực về phía mình nhiều hơn.
Cám ơn bài giảng của thầy rất nhiều.
[1]
[[0.48915385 0.51084615]]
ㅜㅗㅑㄷ뎔 ㅏㅑ두 소ㅕ ㅠㅐ ㅑㅅㅎㅇㄶㄶㅎㅎㄴㅇㅎㄹㄴ
[1]
[[0.48915385 0.51084615]]
Rất tuyệt vời, cảm ơn Thầy
[1]
[[0.48915385 0.51084615]]
Rất tuyệt vời, cảm ơn Anh Thành Long đã có 1 khóa học đem lại nhiều giá trị.
[1]
[[0.48915385 0.51084615]]
học được nhiều giá trị
[1]
[[0.48915385 0.51084615]]
Rất ok
[1]
[[0.48915385 0.51084615]]
Rất hay, em cảm ơn thầy nhiều lắm ạ!
[1]
[[0.48915385 0.51084615]]
Qua tot
[1]
[[0.48915385 0.51084615]]
Khóa học quá hữu ích!
[1]
[[0.48915385 0.51084615]]
Bài học tuyệt vời cảm ơn thầy
[1]
[[0.48915385 0.51084615]]
Bổ ích
[1]
[[0.48915385 0.51084615]]
Like
[1]
[[0.489

[[0.48915385 0.51084615]]
Chuẩn
[1]
[[0.48915385 0.51084615]]
rất hay
[1]
[[0.48915385 0.51084615]]
kien thuc hay
[1]
[[0.48915385 0.51084615]]
*******
[1]
[[0.48915385 0.51084615]]
có những  kiến thức thật sự bổ ích cho phụ nữ, bây giờ em mới hiểu.thanks cô.
[1]
[[0.48915385 0.51084615]]
very good, khoa hoc rat la hay va bo ich
[1]
[[0.48915385 0.51084615]]
Một khóa học rất thú vị, đặc biệt là phần ứng dụng kiến thức marketing vào nghệ thuật quyến rũ ^^
[1]
[[0.48915385 0.51084615]]
Khóa học rất bổ ích nhờ mai tình yêu mà mình khám phá ra nhiều điều mà trước đây mình không bao giờ ngờ đến trong một mối quan hệ
[1]
[[0.48915385 0.51084615]]
ĐÁNH GIÁ KHÓA HỌC (+2 ĐIỂM)
[1]
[[0.48915385 0.51084615]]
khóa học hay, nội dung chi tiết
[1]
[[0.48915385 0.51084615]]
hihi hay quá ạ!!! em cảm ơn chị Mai Tình Yêu thiệt nhiều nha <3 nhờ có chị mà em đã thoát ế hahahaha
[1]
[[0.48915385 0.51084615]]
Khóa học rất hay, cảm ơn bạn
[1]
[[0.48915385 0.51084615]]
Khóa học hay những điêu ch

[1]
[[0.48915385 0.51084615]]
rất dễ hiểu
[1]
[[0.48915385 0.51084615]]
good
[1]
[[0.48915385 0.51084615]]
anh có thể giảng chậm hơn một chút ko ạ?còn anh giảng rất dễ hiểu
[1]
[[0.48915385 0.51084615]]
Hay !!!! Cám ơn anh Tú vì giáo trình này.
[1]
[[0.48915385 0.51084615]]
Nhiều kỹ thuật hay quá~ cám ơn anh Tú
[1]
[[0.48915385 0.51084615]]
khóa học rất bổ ích
[1]
[[0.48915385 0.51084615]]
Dạy tốt 
[1]
[[0.48915385 0.51084615]]
Bài giảng rất hay
[1]
[[0.48915385 0.51084615]]
Khóa học rất hay và bổ ích. giảng viên đẹp trai và chất lượng <3
[1]
[[0.48915385 0.51084615]]
ok hay. hơi nhanh nhưng cũng ổn
[1]
[[0.48915385 0.51084615]]
Q
[1]
[[0.48915385 0.51084615]]
hơi nhiều bài học học mãi mới hết :))
[1]
[[0.48915385 0.51084615]]
sao tự nhiên mình lại ko load được bài giảng nhỉ?
[1]
[[0.48915385 0.51084615]]
thanks, tú sempai cố gắng học cảm âm thôi.
[1]
[[0.48915385 0.51084615]]
rat tuyệt vời và bổ ích ak
[1]
[[0.48915385 0.51084615]]
quá hay,ảm ơn anh haketu
[1]
[[0.48915385 0.5

[[0.48915385 0.51084615]]
Khóa học rất bổ ích cho các bạn theo nghề DBA, đặc biết là các bạn mới vào nghề :). Khóa học cung cấp đầy đủ kiến thức để 1 người DBA có thể quản trị và vận hành 1 CSDL. Chúc giảng viên có nhiều sức khỏe và sắp tới cung cấp thêm các khóa học advance về oracle DB để mọi người có thêm kiến thức chuyên sâu.
[1]
[[0.48915385 0.51084615]]
Khoá học hay, cần thiết cho những người mới học về Oracle database.
[1]
[[0.48915385 0.51084615]]
Biên soạn bài giảng tỉ mỉ.
[1]
[[0.48915385 0.51084615]]
many thanks abcdemdkkdkdkdkđ
[1]
[[0.48915385 0.51084615]]
Nội dung rất phù hợp cho DBA Oracle
[1]
[[0.48915385 0.51084615]]
Serie này quá hay anh  ơi !
[1]
[[0.48915385 0.51084615]]
nội dung khóa học quá hay, đáp ứng được kiến thức phục vụ công việc
[1]
[[0.48915385 0.51084615]]
Nhập nội dung đánh giá
[1]
[[0.48915385 0.51084615]]
Cảm ơn anh đã chia sẽ khóa học :D
[1]
[[0.48915385 0.51084615]]
thầy giáo nhiệt tình, tận tâm
[1]
[[0.48915385 0.51084615]]
Khóa học rất bổ ích cho

[1]
[[0.48915385 0.51084615]]
Khóa học rất hay và ý nghĩa!
[1]
[[0.48915385 0.51084615]]
ok
[1]
[[0.48915385 0.51084615]]
hay quá quá hay!
[1]
[[0.48915385 0.51084615]]
Rất thiết thực trong việc nuôi dạy con
[1]
[[0.48915385 0.51084615]]
Tuyệt vời. Cám ơn Thầy..
[1]
[[0.48915385 0.51084615]]
Cảm ơn thầy. Rất hay.
[1]
[[0.48915385 0.51084615]]
cảm ơn thầy, bài học học rất hữu ích ạ
[1]
[[0.48915385 0.51084615]]
Nội dung bài học rất hay, nhưng nhạc thì to quá giọng thầy giảng thì nhỏ quá
[1]
[[0.48915385 0.51084615]]
19 TUYỆT CHIÊU NUÔI DẠY CON THÀNH TÀI
[1]
[[0.48915385 0.51084615]]
It is a nice course! Apply to our kids!
[1]
[[0.48915385 0.51084615]]
khóa học bổ ích. thầy dạy dễ hiểu.
[1]
[[0.48915385 0.51084615]]
khóa học rất tuyệt vời
[1]
[[0.48915385 0.51084615]]
Thầy dạy dễ nghe, dễ hiểu,đúng là tuổi không đợi tài,à nhầm , phải là tài không đợi tuổi.
[1]
[[0.48915385 0.51084615]]
Khá là hay! Rất pro :))
[1]
[[0.48915385 0.51084615]]
Khóa học thật là tuyệt vời cám ơn unica đã mang l

[1]
[[0.48915385 0.51084615]]
Giảng viên vui tính, giảng hay.
[1]
[[0.48915385 0.51084615]]
Minh đả học thử và thấy rất hửu ích
[1]
[[0.48915385 0.51084615]]
Đang học thử, hy vọng là sẽ ổn với mọi người muốn học từ đầu
[1]
[[0.48915385 0.51084615]]
bài giảng hay và dễ hiểu
[1]
[[0.48915385 0.51084615]]
Rất hay, cảm ơn cô Thảo Trần
[1]
[[0.48915385 0.51084615]]
hoc de hieu va hieu qua
[1]
[[0.48915385 0.51084615]]
tuyệt vời ạ
cảm ơn cô giáo

[1]
[[0.48915385 0.51084615]]
hay qua a. em hoc tot hon nhieu lam


[1]
[[0.48915385 0.51084615]]
Cô dạy hay dễ hiểu, nhiều kiến thức bổ ích
[1]
[[0.48915385 0.51084615]]
Rất tốt
[1]
[[0.48915385 0.51084615]]
Khoá học rất hay cho bạn mất gốc
[1]
[[0.48915385 0.51084615]]
verry good
rất có ích
[1]
[[0.48915385 0.51084615]]
Khoá học quá tuyệt vời. Cám ơn unica nhiều.
[1]
[[0.48915385 0.51084615]]
asdfghjFGHFGHJKLKadsdaadasa
[1]
[[0.48915385 0.51084615]]
tuyệt vời
[1]
[[0.48915385 0.51084615]]
Cô đã xinh lại còn dậy hay nữa
[1]
[[0.48915385 0.5108

[[0.48915385 0.51084615]]
nội dung hấp dẫn, cảm ơn unica
[1]
[[0.48915385 0.51084615]]
Mình mua khóa học này cho ông xã. Ông xã mình rất thích. Đặc biệt là mấy động tác làm giảm stress.
[1]
[[0.48915385 0.51084615]]
nội dung khoá học tuyệt vời. Thầy giáo dậy rất dễ hiểu
[1]
[[0.48915385 0.51084615]]
tuyệt vờiyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyuuuuuuuuuuuuuuuu
[1]
[[0.48915385 0.51084615]]
tuyệt vờiyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyuuuuuuuuuuu
[1]
[[0.48915385 0.51084615]]
tuyệt vờiyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyuuuuuuuuuuuuuu
[1]
[[0.48915385 0.51084615]]
tuyệt vờiyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyuuuuuuuuuuuuuuu
[1]
[[0.48915385 0.51084615]]
hay lam thay oi dung cai em dang can
[1]
[[0.48915385 0.51084615]]
Khóa học bổ ích cho người mới 
[1]
[[0.48915385 0.51084615]]
khóa học hay
[1]
[[0.48915385 0.51084615]]
rất hay
[1]
[[0.48915385 0.51084615]]
Tuyệt vời
[1]
[[0.48915385 0.51084615]]
OK
[1]
[[0.48915385 0.5108

[[0.48915385 0.51084615]]
Tuyệt vời ông mặt trời
[1]
[[0.48915385 0.51084615]]
Khoá học quá tuyệt vời!
[1]
[[0.48915385 0.51084615]]
Rất tuyệt. Hi vọng có thêm nhiều khóa học quý giá như thế này từ Thầy Long ah.
[1]
[[0.48915385 0.51084615]]
khóa  học rất hay...
[1]
[[0.48915385 0.51084615]]
Ngắn gọn dễ hiểu. Rất sát thực tế.
[1]
[[0.48915385 0.51084615]]
Cảm ơn thầy, khóa học rất hay và bổ ích.
[1]
[[0.48915385 0.51084615]]
Hay quá
[1]
[[0.48915385 0.51084615]]
Nhập nội dung đánh giá
[1]
[[0.48915385 0.51084615]]
bài học của thầy rất hay và bổ ích
[1]
[[0.48915385 0.51084615]]
Tuyệt chiêu của Thầy là tuyệt đỉnh!
[1]
[[0.48915385 0.51084615]]
Thật tuyệt vời ! Cảm ơn Thầy !!
[1]
[[0.48915385 0.51084615]]
Những chiến lược đơn giản dễ thực hiện! Hôm nay tôi đã dùng câu thần chú " anh chị giúp em" và đã thành công ngay khi sử dụng. Thật vì diệu!!! Em xin trân thành cảm ơn Thầy và êkip thực hiện khoá học này!!!!
[1]
[[0.48915385 0.51084615]]
Khóa học quá tuyệt vời! Cảm ơn thầy và các cộng s

Đồng nghiệp tôi vô cùng bất ngờ về buổi thuyết trình của tôi ngày hôm qua. Tôi thực sự cảm thấy hài lòng về khóa học này.
[1]
[[0.48915385 0.51084615]]
NGHỆ THUẬT QUYẾN RŨ KHÁN GIẢ TRONG THUYẾT TRÌNH
[1]
[[0.48915385 0.51084615]]
ok
[1]
[[0.48915385 0.51084615]]
khóa học dở nhất mà tôi đăng kí từ trước tới giờ  ..
[1]
[[0.48915385 0.51084615]]
Mình học được nhiều kiến thức mới.
[1]
[[0.48915385 0.51084615]]
Cảm ơn unica đã cung cấp khóa học chất lượng.
Cảm ơn anh Hải đã chia sẻ rất chuyên sâu, rõ ràng, dễ hiểu.
Mong ad sẽ bổ sung thêm tài liệu anh Hải chia sẻ trong khóa học.
Cảm ơn rất nhiều!
[1]
[[0.48915385 0.51084615]]
Mình thấy khoá học rất hay
[1]
[[0.48915385 0.51084615]]
hay
[1]
[[0.48915385 0.51084615]]
rất hay cảm ơn anh nhiều lắm
[1]
[[0.48915385 0.51084615]]
khóa học tuyệt vời quá
[1]
[[0.48915385 0.51084615]]
khóa học hay
[1]
[[0.48915385 0.51084615]]
Tốt
[1]
[[0.48915385 0.51084615]]
ok
[1]
[[0.48915385 0.51084615]]
great
[1]
[[0.48915385 0.51084615]]
Khoá học tốt
[1]
[[0.

quá hay
[1]
[[0.48915385 0.51084615]]
Thanks 
[1]
[[0.48915385 0.51084615]]
cách day soi đong lam hung thu học
[1]
[[0.48915385 0.51084615]]
thả tim
[1]
[[0.48915385 0.51084615]]
khóa học này hay
[1]
[[0.48915385 0.51084615]]
email đoc thay
[1]
[[0.48915385 0.51084615]]
Khóa học rất dễ hiểu
[1]
[[0.48915385 0.51084615]]
Quy trình và hệ thống chăm sóc rất tuyệt.
Ai muốn đky khóa này thì có thể dùng Coupon "Unica69"
Hoặc vào Link sau đây để nhận ƯU ĐÃI nhé: https://unica.vn/vua-email-marketing?aff=14437&coupon=unica&ref=unica69 
[1]
[[0.48915385 0.51084615]]
khóa học rất tốt. 
[1]
[[0.48915385 0.51084615]]
Cảm ơn thầy hay lắm
[1]
[[0.48915385 0.51084615]]
Cảm ơn thầy Hán Quang Dự đã cho tôi những kiến thức rất bổ ích về email marketing. Học xong áp dụng được luôn
[1]
[[0.48915385 0.51084615]]
gg
[1]
[[0.48915385 0.51084615]]
thanks!
[1]
[[0.48915385 0.51084615]]
Quá hay.. cảm ơn thầy Dự. Học cùng mình nhé. Nhập coupon "trongvsp" giảm 40%
[1]
[[0.48915385 0.51084615]]
Cảm ơn Hán

[1]
[[0.48915385 0.51084615]]
Kiến thức tổng quan, rất bổ ích. Cảm ơn Thầy
[1]
[[0.48915385 0.51084615]]
Nhập nội dung đánh giá
[1]
[[0.48915385 0.51084615]]
Hữu ích cho bản thân tôi
[1]
[[0.48915385 0.51084615]]
bài học vô giá, Bạn nên học nó để biết mình đang ở đâu và nên làm gì để có được thành công
[1]
[[0.48915385 0.51084615]]
Thầy tuyệt vời
[1]
[[0.48915385 0.51084615]]
qúa hay luôn
[1]
[[0.48915385 0.51084615]]
Hãy tập trung làm theo những lời Thầy.
[1]
[[0.48915385 0.51084615]]
quá hay
[1]
[[0.48915385 0.51084615]]
Chân thành cảm ơn!
Regardes/ Mr Hạnh
[1]
[[0.48915385 0.51084615]]
thầy dạy quá hay, em cảm ơn thầy
[1]
[[0.48915385 0.51084615]]
Khoá học rất tuyệt!
Trân trọng cảm ơn Thày!
[1]
[[0.48915385 0.51084615]]
hay xuất sắc
[1]
[[0.48915385 0.51084615]]
Rất hay
[1]
[[0.48915385 0.51084615]]
Bài học rất hữu ích
[1]
[[0.48915385 0.51084615]]
X
[1]
[[0.48915385 0.51084615]]
Chưa hk j cả mà đã báo b đa học dc 7% là sao ad
[1]
[[0.48915385 0.51084615]]
Thầy giảng rất hay
[1]
[

[[0.48915385 0.51084615]]
Cảm ơn anh vì khóa học rất hay.
[1]
[[0.48915385 0.51084615]]
Kiến thức khá hữu dụng và bổ ích!
[1]
[[0.48915385 0.51084615]]
đánh giá cao
[1]
[[0.48915385 0.51084615]]
Mới học 1 bài đã thấy rất tuyệt
[1]
[[0.48915385 0.51084615]]
tuyệt
[1]
[[0.48915385 0.51084615]]
hay
[1]
[[0.48915385 0.51084615]]
Các khoá học của thầy ngọc khoá nào cũng chất cả,thích nhất giọng nói thầy truyền cảm dễ nghe.chúc thầy ngày càng thành công hơn.cảm ơn thầy nhiều
[1]
[[0.48915385 0.51084615]]
Khóa học rất hay, lần đầu tiên sau khi mua xong khóa học và nghe hết các bài giảng vì sức hút của từng bài giảng quá tuyệt vời.
[1]
[[0.48915385 0.51084615]]
Quá tuyệt vời!!! Cảm ơn Unica! Cảm ơn Thầy Nguyễn Quang Ngọc ạ!
[1]
[[0.48915385 0.51084615]]
Chương trình rất hay! Cảm ơn thầy Nguyễn Quang Ngọc rất nhiều, Chúc thầy và gia đình năm mới bình an, hạnh phúc 
[1]
[[0.48915385 0.51084615]]
Cám ơn Ngọc đã đưa mô hình Marketing bão lên online. Mình hiểu hơn lý do data có mà tỷ lệ chuyển đổi 

[[0.48915385 0.51084615]]
Nội dung khóa hoc rất hữu ích
[1]
[[0.48915385 0.51084615]]
Cảm ơn nhiều lắm giảng viên Cat Văn Khôi
[1]
[[0.48915385 0.51084615]]
khoá học rất bổ ích ạ
[1]
[[0.48915385 0.51084615]]
Cảm ơn giảng viên. Nội dung khóa học khá chất lượng!
[1]
[[0.48915385 0.51084615]]
Tuyệt vời. Cảm ơn những kiến thức bổ ích từ thầy
[1]
[[0.48915385 0.51084615]]
khóa học thực tế, kiến thức rất chi tiết, dễ hiểu
[1]
[[0.48915385 0.51084615]]
Bai giang hay, rat can cho thoi kinh doanh hien nay!
[1]
[[0.48915385 0.51084615]]
khóa học rất hay, tuyệt vời
[1]
[[0.48915385 0.51084615]]
khóa học rất bổ ích!!!
[1]
[[0.48915385 0.51084615]]
Khoa hoc rat bo ich, thanks you so much
[1]
[[0.48915385 0.51084615]]
Cảm ơn giảng viên. Nội dung khóa học khá chất lượng!
[1]
[[0.48915385 0.51084615]]
Tuyệt vời. Cảm ơn những kiến thức bổ ích từ thầy
[1]
[[0.48915385 0.51084615]]
khóa học thực tế, kiến thức rất chi tiết, dễ hiểu
[1]
[[0.48915385 0.51084615]]
Bai giang hay, rat can cho thoi kinh doanh 

[1]
[[0.48915385 0.51084615]]
Thú vị! Giảng viên nên relax hơn :-)
[1]
[[0.48915385 0.51084615]]
Hữu ích, phù hợp mọi người
[1]
[[0.48915385 0.51084615]]
khoá học rất ok. hy vọng trang web sẽ phát triển hơn nữa
[1]
[[0.48915385 0.51084615]]
Nội dung trực quan, dễ hiểu.
[1]
[[0.48915385 0.51084615]]
Cảm ơn thầy nhờ những bài học của thầy mà cuộc sống và công việc của em đã thay đổi rất nhiều
[1]
[[0.48915385 0.51084615]]
Chúc bạn gặt hái được nhiều thành công từ khóa học.
[1]
[[0.48915385 0.51084615]]
Chúc bạn gặt hái được nhiều thành công từ khóa học
[1]
[[0.48915385 0.51084615]]
.
[1]
[[0.48915385 0.51084615]]
hay
[1]
[[0.48915385 0.51084615]]
Bài giảng rất hữu ích, nhờ ad tải lên thêm bài tập về sheet metal & forming tool giúp!!!
[1]
[[0.48915385 0.51084615]]
hay the hien duoc * phan can hoc
[1]
[[0.48915385 0.51084615]]
sau khi hoàn thành khóa học này thực sự mà nói thì khóa học chất lượng ko tốt nếu không nói là kém
1. chỉ dạy lý thuyết không dậy thực hành vẽ các mô hình thực tế cơ

[1]
[[0.48915385 0.51084615]]
tot moi tim hieu khoa hoc online, va da mua thu goi hoc ke toan tong hop online 480K. Va that su rat ngac nhien Unica ho tro toi ve thoi gian hoc rat tot va huu it
[1]
[[0.48915385 0.51084615]]
Chuong trinh nay rat huu ich
[1]
[[0.48915385 0.51084615]]
Ok
[1]
[[0.48915385 0.51084615]]
nội dung chi tiết.
[1]
[[0.48915385 0.51084615]]
dễ hiểu hơn mình đi học trực tiếp.
[1]
[[0.48915385 0.51084615]]
ok quá tốt quá hiểu cảm own thầy nhiều
[1]
[[0.48915385 0.51084615]]
khóa học hay, dễ hiểu, có tính ứng dụng cao.
[1]
[[0.48915385 0.51084615]]
bài học rất bổ ích. Rất chi tiết. Mong a cống hiến nhiều thêm cho các học viên mới
[1]
[[0.48915385 0.51084615]]
Bài học khá chi tiết và đầy đủ
Nếu bạn là người mới hoàn toàn chưa biết kế toán và excel thì nó sẽ không phù hợp.
[1]
[[0.48915385 0.51084615]]
Bài giảng hay và chi tiết
[1]
[[0.48915385 0.51084615]]
Good!!
[1]
[[0.48915385 0.51084615]]
Rất hữu ích
[1]
[[0.48915385 0.51084615]]
Thật là tuyệt vời !!!
Mình đã qua 

[1]
[[0.48915385 0.51084615]]
Hướng dẫn rất tốt, đã áp dụng được vào công việc.
[1]
[[0.48915385 0.51084615]]
khóa học trên cả mong đợi ạ
[1]
[[0.48915385 0.51084615]]
Chào thầy thầy dạy rất hay em tiếp thu được nhiều kiến thức từ thầy. Cảm ơn thầy
[1]
[[0.48915385 0.51084615]]
khóa học rất hay, kiến thức thực tế, xin cảm ơn
[1]
[[0.48915385 0.51084615]]
dân sale học thì quá đúng bài
[1]
[[0.48915385 0.51084615]]
Hay cảm on thay và unica
[1]
[[0.48915385 0.51084615]]
Cảm ơn anh Dự về khóa học nhé
[1]
[[0.48915385 0.51084615]]
hay quaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
[1]
[[0.48915385 0.51084615]]
nói rất có thu hút ! chiến lược rất hay :>>>>>>> Hướng dẫn rất tốt, đã áp dụng được thành công vào công việc.
[1]
[[0.48915385 0.51084615]]
Khóa học rất hay và giá trị!
[1]
[[0.48915385 0.51084615]]
Khóa hoc hay rat huu ich xem xong muon lam ngay   ...... Chia se rat nhiet tinh.
[1]
[[0.48915385 0.51084615]]
Bán hàng như hơi thở
[1]
[[0.48915385 0.51084615]]
tuyet voi anh du
[1]
[[0.48

[[0.48915385 0.51084615]]
Quá tuyệt vời !!!
[1]
[[0.48915385 0.51084615]]
Khóa học hay quá bạn Minh ơi, áp dụng cái có sales luôn
[1]
[[0.48915385 0.51084615]]
tuyệt vời
[1]
[[0.48915385 0.51084615]]
Toi hai *g voi *h ma *  ban day toi. hy vong se gat hai duoc thanh cong sau khoa hoc. cam on
[1]
[[0.48915385 0.51084615]]
qua hay, noi dung chuyen sau
[1]
[[0.48915385 0.51084615]]
tam noi chung chua ap dung duoc nhieu
[1]
[[0.48915385 0.51084615]]
Khóa học rất hay, cám ơn tác giả, cám ơn Unica
[1]
[[0.48915385 0.51084615]]
Mỗi khóa học đều có những điều bổ ích rất đáng được học hỏi. Ko thiên lý thuyết và chú trọng vào tính thực tế là điều tôi cảm nhận được ở khóa học này. Cám ơn giảng viên đã cung cấp những kiến thức giá trị. Bản thân tôi cũng đang sở hữu cuốn "Sát thủ bán hàng" và tôi thấy mình đã quyết định đúng khi mua cuốn sách. Xin chân thành cám ơn!
[1]
[[0.48915385 0.51084615]]
xác định tư duy bán hàng, xd Quy trình bán hàng và đội nhóm bán hàng....một bài học tổng hợp khá tốt!

[1]
[[0.48915385 0.51084615]]
ok
[1]
[[0.48915385 0.51084615]]
Xin cho em vào nhóm học
[1]
[[0.48915385 0.51084615]]
Rất tốt tiện cho người ko có nhiều time
[1]
[[0.48915385 0.51084615]]
Bài học rất hữu ích
[1]
[[0.48915385 0.51084615]]
tôi đi học nhiều nơi ở đây trình độ dạy tốt quá nên tôi phải theo học  bằng được cảm ơn Unica
[1]
[[0.48915385 0.51084615]]
Tốt học linh động, tiện lợi cho người đi làm
[1]
[[0.48915385 0.51084615]]
Tuyệtt
[1]
[[0.48915385 0.51084615]]
Xin cảm ơn trung tâm Thanhmaihsk và Unica.
[1]
[[0.48915385 0.51084615]]
Rất hay!
[1]
[[0.48915385 0.51084615]]
Khóa học hay và tiện dụng
[1]
[[0.48915385 0.51084615]]
Rất tốt tiện cho người ko có nhiều time
[1]
[[0.48915385 0.51084615]]
Tốt
[1]
[[0.48915385 0.51084615]]
Rất bổ ích
[1]
[[0.48915385 0.51084615]]
Bài học rất hữu ích
[1]
[[0.48915385 0.51084615]]
Hay và dễ học
[1]
[[0.48915385 0.51084615]]
Hiểu tốt
[1]
[[0.48915385 0.51084615]]
Phù hợp nhu cầu giao tiếp.
[1]
[[0.48915385 0.51084615]]
tôi đi học nhiều nơi ở đ

[[0.48915385 0.51084615]]
Dạy mông lung quá,nói rộng mà không giải thích
[1]
[[0.48915385 0.51084615]]
PHONG THỦY NHÀ Ở CĂN BẢN
[1]
[[0.48915385 0.51084615]]
Khoá học hữu ích, cung cấp phương pháp đầu tư chứng khoán, các bạn mới muốn đầu tư nên học để tránh những sai lầm do thiếu kiến thức hoặc vội vàng nghe theo tin đồn mua cổ phiếu thua lỗ.
[1]
[[0.48915385 0.51084615]]
Tuyệt vời, cảm ơn giảng viên
[1]
[[0.48915385 0.51084615]]
bài học rất hữu ích và giá trị
[1]
[[0.48915385 0.51084615]]
Cảm ơn Thầy Hoàng!
Đã chia sẻ chân thành.
[1]
[[0.48915385 0.51084615]]
bài học hay và hữu ích cho nhà đầu tư
[1]
[[0.48915385 0.51084615]]
Khóa học rất hay, cảm ơn thầy
[1]
[[0.48915385 0.51084615]]
rất cám ơn anh đã chia sẻ
[1]
[[0.48915385 0.51084615]]
cam on giang vien
[1]
[[0.48915385 0.51084615]]
ok,tksddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
[1]
[[0.48915385 0.51084615]]
Tốt lấm Mr Hoàng
[1]
[[0.48915385 0.51084615]]
Nội dung rất cơ bản, ngắn gọn
[1]


In [12]:
len(list(set(x_train)))

346